name: Codex auto-debug & patch

on:
  push:
    paths:
      - "src/App.js"        # re-debug when App.js changes
  workflow_dispatch:        # manual trigger button in the UI

jobs:
  codex:
    runs-on: ubuntu-latest

    steps:
      # 0) Check out your repository
      - uses: actions/checkout@v4

      # 1) Install your app's deps (puts react-scripts on disk)
      - name: Install dependencies
        run: npm ci

      # 2) Install the Codex CLI
      - name: Install Codex CLI
        run: npm i -g @openai/codex@latest

      # 3) Let Codex fix or extend App.js, then run tests
      - name: Codex auto-edit
        env:
         OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
         codex --full-auto --yes --quiet \
          "Fix getUserStats so Questions Answered counts all forecasts, then run npm test."

      # 4) Create a pull request with the patch
      - name: Open PR with patch
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "🤖 Codex patch"
          title: "Codex-generated update"

